name: hybrid-ntk
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Core Python ---
  - python=3.11

  # --- Scientific Computing & Data ---
  - numpy=1.26
  - scikit-learn=1.4
  - fetch-openml # This is part of scikit-learn but explicitly listed for clarity

  # --- Visualization & Utilities ---
  - matplotlib=3.8
  - jupyterlab
  - pip

  # --- JAX and its dependencies (installed via pip) ---
  - pip:
    - jax==0.4.26
    - jaxlib==0.4.26
