name: hybrid_ntk # Note the underscore here!
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - scikit-learn=1.4
  - matplotlib=3.8
  - jupyterlab
  - notebook
  - ipykernel
  - pip
  - pip:
      - jax==0.4.26
      - jaxlib==0.4.26
